CREATE TABLE SUBJECTS (ID SERIAL PRIMARY KEY, NAME TEXT NOT NULL UNIQUE);
CREATE TABLE GRADES (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL UNIQUE,
    YEAR SMALLINT NOT NULL DEFAULT DATE_PART('year', CURRENT_DATE)
);
CREATE TABLE TEACHERS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL
);
CREATE TABLE STUDENTS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    GRADE_ID INT REFERENCES GRADES (ID)
);
CREATE TABLE COURSES (
    ID SERIAL PRIMARY KEY,
    TEACHER_ID INT NOT NULL REFERENCES TEACHERS (ID),
    SUBJECT_ID INT NOT NULL REFERENCES SUBJECTS (ID),
    GRADE_ID INT NOT NULL REFERENCES GRADES (ID),
    CONSTRAINT uk_course UNIQUE (TEACHER_ID, SUBJECT_ID, GRADE_ID)
);
CREATE TABLE LESSONS (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL REFERENCES COURSES (ID),
    GRADE_ID INT NOT NULL REFERENCES GRADES (ID),
    DAY DATE NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL
);
CREATE TABLE REGISTRATIONS (
    id serial primary key,
    date date not null,
    lesson_id int not null references LESSONS (id),
    student_id int not null references STUDENTS (id)
);